import { HeadComponentProps } from "../../types";
export default function BaseHead({
  title,
  iconPath = "/favicon.ico",
}: HeadComponentProps) {
  return (
    <>
      <title>{title}</title>
      <link rel="icon" href={iconPath} />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
